name: draftkings_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.8.4
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  flutter_inappwebview: ^5.8.0
  get_it: ^7.6.4
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  loading_animation_widget: ^1.2.0+4
  flutter_countdown_timer: ^4.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.1.1
  build_runner: ^2.4.4

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/loading/
    - assets/images/onboarding/
    - assets/images/elements/
    - assets/images/news/
    - assets/images/news/basketball/
    - assets/images/news/football/
    - assets/images/quiz/
    - assets/images/quiz/quiz-1/
    - assets/images/quiz/quiz-2/
    - assets/images/quiz/quiz-3/
    - assets/images/puzzle/
    - assets/images/puzzle/basketball/1/
    - assets/images/puzzle/basketball/2/
    - assets/images/puzzle/basketball/3/
    - assets/images/puzzle/basketball/4/
    - assets/images/puzzle/basketball/5/
    - assets/images/puzzle/basketball/6/
    - assets/images/puzzle/basketball/7/
    - assets/images/puzzle/basketball/8/
    - assets/images/puzzle/basketball/9/
    - assets/images/puzzle/basketball/10/
    - assets/images/puzzle/football/
    - assets/images/puzzle/football/1/
    - assets/images/puzzle/football/2/
    - assets/images/puzzle/football/3/
    - assets/images/puzzle/football/4/
    - assets/images/puzzle/football/5/
    - assets/images/puzzle/football/6/
    - assets/images/puzzle/football/7/
    - assets/images/puzzle/football/8/
    - assets/images/puzzle/football/9/
    - assets/images/puzzle/football/10/


  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-Black.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"